package de.whoopwh00p.taskapp.controller.dto;

import de.whoopwh00p.taskapp.model.TaskState;
import io.micronaut.core.annotation.Introspected;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.Setter;

import javax.validation.Valid;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

@Getter
@Setter
@Introspected
public class TaskResponseDto {

    @Schema(description = "Unique ID of the task. Autogenerated.", example = "1")
    private int id;

    @Schema(description = "The project id that the task belongs to")
    private Integer projectId;

    @Schema(description = "The name of the task", example = "eat pizza")
    private String name;

    @Schema(description = "the detailed description of the task", example = "the pizza has to be eaten")
    private String description;

    @Schema(description = "the state of the task", example = "TODO")
    private TaskState state;

    @Schema(description = "the id of the assignee", example = "1")
    private String assigneeId;

    @Schema(description = "the name of the assignee", example = "John.Doe@example.com")
    private String assigneeName;
}
