package de.whoopwh00p.taskapp.model;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import javax.persistence.*;

@Data
@Entity
public class Task {
    @Id
    @GeneratedValue
    @Schema(name = "unique ID. Autogenerated.")
    private int id;

    @ManyToOne
    @JoinColumn(name = "project_id", nullable = false)
    @Schema(description = "The project that the task belongs to")
    private Project project;

    @Schema(description = "The name of the task", example = "eat pizza")
    private String name;

    @Schema(description = "the detailed description of the task", example = "the pizza has to be eaten")
    private String description;

    @Enumerated(EnumType.STRING)
    @Schema(description = "the state of the task", example = "TODO")
    private TaskState state;
}

