package de.whoopwh00p.taskapp.model;

import com.sun.istack.Nullable;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Data
@Entity
public class Task {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(name = "unique ID. Autogenerated.")
    private int id;

    @ManyToOne
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    private String name;

    private String description;

    @Enumerated(EnumType.STRING)
    private TaskState state;

    @ManyToOne
    @JoinColumn(name = "creator_id")
    private User creator;
}

