package de.whoopwh00p.taskapp.model;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import javax.persistence.*;
import java.util.Set;

@Data
@Entity
public class User {
    @Id
    @GeneratedValue
    @Schema(name = "unique ID. Autogenerated.")
    private int id;

    @ManyToMany(cascade = { CascadeType.ALL })
    @JoinTable(
            name = "User_Project",
            joinColumns = { @JoinColumn(name= "user_id")},
            inverseJoinColumns = { @JoinColumn(name= "project_id")}
    )
    @Schema(implementation = Project.class, description = "The projects that belong to the user")
    private Set<Project> projects;

    @Schema(description = "the name of the user", example = "John Doe")
    private String name;
}
