micronaut:
  application:
    name: task-app
  security:
    enabled: false
    token:
      jwt:
        enabled: false #set to true, to enable secured endpoints
        signatures:
          jwks:
            auth0:
              url: 'https://dev-cd3cebbk.eu.auth0.com/.well-known/jwks.json'
  openapi:
    views:
      spec:
        swagger-ui:
          enabled: true
          theme: flattop
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    packages-to-scan:
      - 'de.whoopwh00p.taskapp.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true